EXP:
    ID: voc12
    OUTPUT_DIR: data

DATASET:
    NAME: vocaug
    ROOT: /home/lianghuizhu/data/VOC2012/VOCdevkit
    LABELS: ./data/datasets/voc12/labels.txt
    N_CLASSES: 21
    IGNORE_LABEL: 255
    SCALES: [0.5, 0.75, 1.0, 1.25, 1.5]
    SPLIT:
        TRAIN: train_aug_cls
        VAL: val_cls
        TEST: test

DATALOADER:
    NUM_WORKERS: 6

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    STD:
        R: 0.27473737
        G: 0.27164029
        B: 0.28467983
    SIZE:
        BASE: # None
        TRAIN: 381
        TEST: 513

MODEL:
    NAME: DeepLabV3Py_ResNet101_MSC
    N_BLOCKS: [3, 4, 23, 3]
    ATROUS_RATES: [6, 12, 18, 24]
    INIT_MODEL: /home/lianghuizhu/Project8_WSSS/reference/DRS/DeepLab-V2-PyTorch/pretrained/deeplabv1_resnet101-coco.pth

SOLVER:
    BATCH_SIZE:
        TRAIN: 8
        TEST: 1
    ITER_MAX: 10000
    ITER_SIZE: 2
    ITER_SAVE: 2000
    ITER_TB: 50
    LR_DECAY: 10
    LR: 2.5e-4
    MOMENTUM: 0.9
    OPTIMIZER: sgd
    POLY_POWER: 0.9
    WEIGHT_DECAY: 5.0e-4
    AVERAGE_LOSS: 20

CRF:
    ITER_MAX: 10
    POS_W: 3
    POS_XY_STD: 1
    BI_W: 4
    BI_XY_STD: 67
    BI_RGB_STD: 3
